[theme]
base = "light"
primaryColor = "#A25A3C"               # Soft aesthetic brown
backgroundColor = "#FFF9F5"            # Cream peach background
secondaryBackgroundColor = "#F7F1EB"   # Light beige cards
textColor = "#3C2F2F"                  # Deep brown text
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
