[theme]
base = "light"
primaryColor = "#A25A3C"
backgroundColor = "#FFF9F5"
secondaryBackgroundColor = "#F7F1EB"
textColor = "#3C2F2F"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
